var GAME_LEVELS = [

  ["                                                                            ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxx!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxx!!!!!x!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvxxxxxxxxxxxxxxxxx",
   "xxx!!!x!!!!!x!!xxxxx                                          xxxx!!!xx!!xxx",
   "xxxx!!!!!!!!!!!!xxx                                             xx!xx!!x!!xx",
   "x!!!!!!!!!v!!!!!!!!                                              !!!!!!!!!!x",
   "x!!!!                                                              !!!!!!!!x",
   "x                                                                    !!!!!!x",
   "x                                                  xx                 !!!!!x",
   "x  o                                             xxxx                   !!!x",
   "x                                   xxxxxxxxxxxxxxxxx                      x",
   "xxxxxxxxxxxxxxx         o           xxvxxxxxxxxxxxxxx                      x",
   "xxxxxx                                             xx    xxx    xxxx       x",
   "xx                    xxxxxx                       xx!!!!!!!!!!!!xxx       x",
   "xx                 xxx!!!!!!xxxx                   xx!!!!!!!!!!!!xxx      =x",
   "xx             xxxxx!!!!xx!!!!xxxx                 xxxxxxxxxxxxxxxxx       x",
   "xx  @               xx!!!!!!xx     xxxxxx       o  xx                      x",
   "xxxxxxxx              xxxvxx                       xx  o                   x",
   "xx!!!!!x                                      xxxxxxx                      x",
   "xx!!!!!x      o                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xx!!!!!!                                      xxxxxx!!!!!!!x!!!!!x!!!!!!!xxx",
   "xx!x!!x!!    xxx                      xxxxxxx xxxxx!!!x!!!!!!!!!!!!!!!!!!xxx",
   "xx!!!!!!!!                                    xxx!!!!!!!!x!!!!!!!!!!!!!!xxxx",
   "xx!!!!x!!!!!       xxxxxxxxxxxxxx             x!!!!!!!!!!!!!!!!!!x!!!!xxxxxx",
   "xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!xxxxxxx",
   "xx!x!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!xxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                            "],
  ["                                                                        ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxvxxxxxxxxvxxxxxxxvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxx",
   "xx                                                x            xxx!!!xxx",
   "xx                                                x       o    xxxx!!!xx",
   "xx                                                x            xxxxxxxxx",
   "xx            o                                   xxxxxyxxxxxxxxxxxxx!!!",
   "xx  @                                             xxxxxxxxxxxxxxxxxx!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                xxxx!!!",
   "!!!!!!!!xx               x                                       xxx!!!!",
   "!!!!!xxx     o           x          xxxxxxxxxx                   xxxx!!!",
   "!!!!xx                   x                       xxxxxxxxx       xxx!!x!",
   "!!!xxxxxxxxxxxxxxxxx     x!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx      =xx!!!!!",
   "!!x                      x!!!!x!!!!x!!!!x!!!!!x!!!!!!x!!xx       xxx!x!!",
   "!!x                      xxxxvxxxxxxvxxxxxx!!!!!!!x!!!!!xx       xxx!!!!",
   "!!xx                                       xx!!!!!!!!!!!xx       xxxx!!!",
   "!!!!xx                                     xx!!!!!!x!!!xxx   o   xxxxx!!",
   "!!!!!xx                                     xx!!x!!!!!!!xx       xxxxx!!",
   "!!!!!!xxxx                                   xxxx!!!!!x!xx       xxx!x!!",
   "!!x!!!!!!xxx#xx                                 xx!x!!!!xx=      xxx!!!!",
   "!!!!!!!x!xxxxxxxx                                 xxxxxxxx       xxxxx!!",
   "!!!!x!!!!!!!xxxxxxx       x      x     xxx             xxx       xxxx!!!",
   "!!!!!!!x!!!!!!xxxxxxx     x      x     xxxx                      xxx!!!!",
   "!x!!!!!!!!!!!!!!xxxxxx!!!!!!!!!!!!!!!!!!!!!x                     xx!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!",
   "                                                                        "],
   ["                                                                            ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxx!!x!!!!!x!!!!!!!                                                     xxx",
    "xx!!x!!!x!!!!!!!                                                          xx",
    "xx!!!!!!!!!!                                        xxxxxxxxxxxxxxx        x",
    "x!!!                            o               xxxxxxxx!!!!!x!!xxx        x",
    "x!                                            xxx!!xxx!!x!!!!!!x!xx     o  x",
    "x                     *                 xxxxxxxvxxxxv!!!!!!x!!!!!xx        x",
    "x                                                      !!!!!!!x!xxx        x",
    "x                xxxxxxxxx                                 !!!!xxxx        x",
    "x       xxxxxxxxxxxx                                              x  o     x",
    "x                                                                 x        x",
    "x                                      xxxx                       x        x",
    "xxx                                    xx!!                       x        x",
    "!!!!                                   xx!!   xxx                 x        x",
    "!!x!xxx       o                        xx!!!!                          o   x",
    "!!!!!!!                                xx!!!!!!!!! xxx                     x",
    "x!x!!!!!    xxxxxxxx                   xxxx!!!!x!!!!!!!!!xx                x",
    "x!!!!x!!!!!!x!!xx!!xxxxxx              xxxxvxxxxxxxxvxxxxxxxxxvxxxxxxxxxxxxx",
    "xx!!x!!!!!x!!!!!x!!!!!!=               xx                               !!!x",
    "xxx!xxxx!!!xxxxxxx!!!!         xxx                                        !x",
    "xx                             x!x                                    o   !x",
    "xxx                            x!xxxx                                     !x",
    "xxxx   @                       x!!!!xxxxx      !          !              !!x",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],


    ["                                                                           ",
    "                                                                            ",
    "                                                                            ",
    "                                                                            ",
    "                                                                            ",
    "           xxxxxxx   xx     x   xxxxxx     xx                               ",
    "           x         x x    x   x     x    xx                               ",
    "           xxxxx     x  x   x   x      x   xx                               ",
    "           x         x   x  x   x      x   xx                               ",
    "           x         x    x x   x     x                                     ",
    "           xxxxxxx   x     xx   xxxxxx     xx                               ",
    "                                                                            ",
    "                                                                            ",
    "                                                                            ",
    "                                                                            ",
    "                                                                            ",
    "  @                                                                         ",
    " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
    "                                                                            ",]

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
